import { PALETTES } from './palettes';

export const TEMPLATES = [
  {
    id: 'vogue-cover',
    name: 'The Cover',
    category: 'Cover',
    palette: 'obsidian',
    description: 'Full-bleed hero portrait with editorial masthead. Vogue-inspired.',
    fields: [
      { id: 'bgImage',     type: 'image',    label: 'Cover Image',    required: true, hint: 'Portrait orientation works best' },
      { id: 'masthead',    type: 'text',     label: 'Masthead',       default: 'LWD', maxLength: 6 },
      { id: 'issueLabel',  type: 'text',     label: 'Issue Label',    placeholder: 'Issue 01 · Spring 2026' },
      { id: 'title',       type: 'textarea', label: 'Cover Title',    placeholder: 'THE BRIDAL\nEDITION', required: true, hint: 'Use line breaks to split across 2 lines' },
      { id: 'credits',     type: 'text',     label: 'Credits / Designers', placeholder: 'Vera Wang · Elie Saab · Marchesa' },
    ],
  },
  {
    id: 'the-gown',
    name: 'The Gown',
    category: 'Bridal',
    palette: 'ivory',
    description: 'Full-length gown portrait with minimal editorial typography. Ivory palette.',
    fields: [
      { id: 'image',       type: 'image',    label: 'Gown / Model Image', required: true, hint: 'Full-length portrait, vertical' },
      { id: 'dressName',   type: 'text',     label: 'Dress Name',     placeholder: 'The Madeleine', required: true },
      { id: 'designer',    type: 'text',     label: 'Designer',       placeholder: 'Vera Wang' },
      { id: 'details',     type: 'text',     label: 'Details',        placeholder: 'Duchess satin · bespoke · made to measure' },
      { id: 'price',       type: 'text',     label: 'Price',          placeholder: 'POA' },
    ],
  },
  {
    id: 'the-jewel',
    name: 'The Jewel',
    category: 'Jewellery',
    palette: 'claret',
    description: 'Floating product shot on deep velvet. Maximum drama for jewellery.',
    fields: [
      { id: 'image',       type: 'image',    label: 'Jewellery Image', required: true, hint: 'Product on dark or transparent background' },
      { id: 'name',        type: 'text',     label: 'Piece Name',     placeholder: 'THE MADELEINE RING', required: true },
      { id: 'details',     type: 'text',     label: 'Details',        placeholder: '18ct white gold · 3.2ct round brilliant' },
      { id: 'brand',       type: 'text',     label: 'Brand',          placeholder: 'Graff, London' },
      { id: 'price',       type: 'text',     label: 'Price',          placeholder: '£48,000' },
      { id: 'bgPalette',   type: 'select',   label: 'Background',     options: ['claret','obsidian','midnight','white'], default: 'claret' },
    ],
  },
  {
    id: 'feature-spread',
    name: 'Feature Spread',
    category: 'Editorial',
    palette: 'white',
    description: 'Large hero image left, headline + editorial copy right. Clean and authoritative.',
    fields: [
      { id: 'image',       type: 'image',    label: 'Hero Image',     required: true },
      { id: 'headline',    type: 'textarea', label: 'Headline',       placeholder: 'SOMETHING\nBORROWED,\nSOMETHING\nGOLD', required: true },
      { id: 'body',        type: 'textarea', label: 'Body Copy',      placeholder: 'Editorial copy goes here. Two to three paragraphs works well for this layout.' },
      { id: 'byline',      type: 'text',     label: 'Photography Credit', placeholder: 'Photography: Studio Name' },
    ],
  },
  {
    id: 'the-runway',
    name: 'The Runway',
    category: 'Fashion',
    palette: 'obsidian',
    description: 'Three-image filmstrip with editorial title below a gold rule. Fashion-forward.',
    fields: [
      { id: 'image1',      type: 'image',    label: 'Image 1 (left)',  required: true },
      { id: 'image2',      type: 'image',    label: 'Image 2 (centre)', required: true },
      { id: 'image3',      type: 'image',    label: 'Image 3 (right)',  required: true },
      { id: 'heading',     type: 'text',     label: 'Heading',          placeholder: 'SPRING / SUMMER 2026', required: true },
      { id: 'designers',   type: 'text',     label: 'Designers',        placeholder: 'Elie Saab · Marchesa · Jenny Packham' },
    ],
  },
  {
    id: 'the-destination',
    name: 'The Destination',
    category: 'Travel',
    palette: 'midnight',
    description: 'Full-bleed landscape with location name in huge italic serif below. Condé Nast Traveller energy.',
    fields: [
      { id: 'image',       type: 'image',    label: 'Landscape / Aerial Image', required: true, hint: 'Landscape orientation works best' },
      { id: 'location',    type: 'text',     label: 'Location Name',  placeholder: 'TUSCANY', required: true },
      { id: 'subline',     type: 'text',     label: 'Subline',        placeholder: 'Italy · June 2026' },
      { id: 'description', type: 'textarea', label: 'Short Description', placeholder: 'Optional — a single atmospheric sentence.' },
    ],
  },
  {
    id: 'the-portrait',
    name: 'The Portrait',
    category: 'Real Wedding',
    palette: 'blush',
    description: 'Full-bleed couple portrait with name overlay. Perfect for real wedding features.',
    fields: [
      { id: 'image',       type: 'image',    label: 'Couple / Portrait Image', required: true },
      { id: 'names',       type: 'text',     label: 'Couple Names',   placeholder: 'Isabella & James', required: true },
      { id: 'location',    type: 'text',     label: 'Wedding Location', placeholder: 'MARRIED IN TUSCANY' },
      { id: 'date',        type: 'text',     label: 'Date',           placeholder: 'June 14 · 2026' },
    ],
  },
  {
    id: 'the-triptych',
    name: 'The Triptych',
    category: 'Detail',
    palette: 'ivory',
    description: 'Three equal portrait images with individual captions. Perfect for detail shots.',
    fields: [
      { id: 'image1',      type: 'image',    label: 'Image 1',        required: true },
      { id: 'image2',      type: 'image',    label: 'Image 2',        required: true },
      { id: 'image3',      type: 'image',    label: 'Image 3',        required: true },
      { id: 'caption1',    type: 'text',     label: 'Caption 1',      placeholder: 'The Bouquet' },
      { id: 'caption2',    type: 'text',     label: 'Caption 2',      placeholder: 'The Ring' },
      { id: 'caption3',    type: 'text',     label: 'Caption 3',      placeholder: 'The Veil' },
      { id: 'credit',      type: 'text',     label: 'Photography Credit', placeholder: 'Photography: Studio Name' },
    ],
  },
  {
    id: 'pull-quote',
    name: 'The Pull Quote',
    category: 'Editorial',
    palette: 'obsidian',
    description: 'Pure typography — huge italic quote on dark. No image. Maximum impact between spreads.',
    fields: [
      { id: 'quote',       type: 'textarea', label: 'Quote',          placeholder: '"A wedding dress is not just a garment. It is an heirloom in waiting."', required: true },
      { id: 'attribution', type: 'text',     label: 'Attribution',    placeholder: '— Vera Wang' },
    ],
  },
  {
    id: 'product-page',
    name: 'Product Page',
    category: 'Fashion',
    palette: 'white',
    description: 'Centered product on white. Net-a-Porter editorial style. Clinical, confident.',
    fields: [
      { id: 'image',       type: 'image',    label: 'Product Image',  required: true, hint: 'Product on white or transparent background' },
      { id: 'name',        type: 'text',     label: 'Product Name',   placeholder: 'MADELEINE PEARL NECKLACE', required: true },
      { id: 'brand',       type: 'text',     label: 'Brand',          placeholder: 'Mikimoto' },
      { id: 'price',       type: 'text',     label: 'Price',          placeholder: '£4,800' },
      { id: 'category',    type: 'text',     label: 'Category',       placeholder: 'Fine Jewellery' },
    ],
  },
  {
    id: 'the-hotel',
    name: 'The Hotel',
    category: 'Venue',
    palette: 'midnight',
    description: 'Split layout — venue image left, elegant description right. Perfect for venue features.',
    fields: [
      { id: 'image',       type: 'image',    label: 'Venue / Interior Image', required: true },
      { id: 'venueName',   type: 'text',     label: 'Venue Name',     placeholder: 'HOTEL CIPRIANI', required: true },
      { id: 'location',    type: 'text',     label: 'Location',       placeholder: 'Venice, Italy' },
      { id: 'description', type: 'textarea', label: 'Description',    placeholder: 'A palazzo suspended above the Grand Canal, where time slows to the pace of gondolas and wedding bells.' },
      { id: 'features',    type: 'textarea', label: 'Features (one per line)', placeholder: 'Private canal entrance\nIn-house floral studio\nDedicated wedding concierge' },
    ],
  },
  {
    id: 'table-of-contents',
    name: 'Contents',
    category: 'Navigation',
    palette: 'ivory',
    description: 'Numbered issue contents page with section titles. Elegant typographic layout.',
    fields: [
      { id: 'issueLabel',  type: 'text',     label: 'Issue Label',    placeholder: 'I S S U E  0 1', required: true },
      { id: 'entries',     type: 'textarea', label: 'Contents Entries (page|title per line)', placeholder: '06|The Wedding Dress\n14|Jewellery Stories\n22|Venues of the Season\n34|Real Wedding: Isabella\n44|The Bridal Beauty Edit\n52|Destination: Tuscany', required: true, hint: 'Format: page number | section title, one per line' },
      { id: 'subtitle',    type: 'text',     label: 'Issue Subtitle', placeholder: 'The Bridal Edition' },
    ],
  },
];

export const CATEGORIES = [...new Set(TEMPLATES.map(t => t.category))];
export default TEMPLATES;
